### ISSUE TITLE
Design for required screens

### ISSUE THREAD

**Issue by emreozcan** [MCBUKimono/frontend#1]
Layouts are required for the frontend implementation.

- [x] Main Page
- [x] Product List Page by Categories
- [x] Product List Page by Search
- [x] Register and Login Page
- [x] Cart Page
- [x] Favorites Page
- [x] Inspection Page
- [x] Check in Page
- [x] Admin Page

**Comment by Erengokce03** [comment]
Work in Progress 1 : [ Main Screen Of The WebSite](https://www.figma.com/design/eNvmaCnjBaZI8o26dsJgkH/Kimono?node-id=0-1&t=Oa7CkMSOtwfJX79K-1)

**Comment by Erengokce03** [comment]
Finished :  [Product List Page by Categories](https://www.figma.com/design/eNvmaCnjBaZI8o26dsJgkH/Kimono?node-id=4-2&t=K9Nx1ggEWsUbXLH0-0)

**Comment by Erengokce03** [comment]
New Pages on the Figma Project - [Login and Register Pages](https://www.figma.com/design/eNvmaCnjBaZI8o26dsJgkH/Kimono?node-id=0-1&t=Oa7CkMSOtwfJX79K-1)

**Comment by Erengokce03** [comment]
New Page Added.

**Comment by Erengokce03** [comment]
Favorites Page is done.

**Comment by Erengokce03** [comment]
Main Page is done and there is color corrections on some pages.

**Comment by Erengokce03** [comment]
Main Page edited -> Added a Search Bar.

**Comment by Erengokce03** [comment]
Admin Page is done.

**Comment by Erengokce03** [comment]
Check In Page is done.

**Comment by Erengokce03** [comment]
All Pages are done.
