### ISSUE TITLE
Create Integration Tests for OrderRepository

### ISSUE THREAD

**Issue by OguzAnilAtes** [MCBUKimono/frontend#18]
Creating Integration Tests for OrderRepository.

**Comment by emreozcan** [comment]
This is the frontend issue tracker. @OguzAnilAtes please move this issue to the backend tracker and recheck the selected issue tracker in the future

**Comment by OguzAnilAtes** [comment]
> This is the frontend issue tracker. [@OguzAnilAtes](https://github.com/OguzAnilAtes) please move this issue to the backend tracker and recheck the selected issue tracker in the future <3

Thanks <3
